# Generated by Django 3.1.1 on 2020-09-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classificacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_inicio', models.DateField(auto_now=True)),
                ('dt_fim', models.DateField(auto_now=True)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=3)),
                ('classificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classificacao.classificacao')),
            ],
        ),
    ]
