# Generated by Django 3.1.1 on 2020-09-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='dt_fim',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='dt_inicio',
            field=models.CharField(max_length=10),
        ),
    ]
