# Generated by Django 3.1.1 on 2020-09-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200922_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viagem',
            name='dt_fim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='dt_inicio',
            field=models.DateField(),
        ),
    ]
